
[Li]
r_atoms = [[0.0, 0.0, 0.0]]
z_atoms = [3.0]
n_el_atoms = [3]
n_el = 3

[LiH]
r_atoms = [[0.0, 0.0, 0.0], [1.595, 0.0, 0.0]]
z_atoms = [3.0, 1.0]
n_el_atoms = [3, 1]
n_el = 4

[He]
r_atoms = [[0.0, 0.0, 0.0]]
z_atoms = [2.0]
n_el_atoms = [2]
n_el = 2

[Be]
r_atoms = [[0.0, 0.0, 0.0]]
z_atoms = [4.0]
n_el_atoms = [4]
n_el = 4

[B]
r_atoms = [[0.0, 0.0, 0.0]]
z_atoms = [5.0]
n_el_atoms = [5]
n_el = 5

[C]
r_atoms = [[0.0, 0.0, 0.0]]
z_atoms = [6.0]
n_el_atoms = [6]
n_el = 6

[HEG]
periodic_boundaries = true
real_basis = [[1.0,  0.0,  0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]


[LiSolid]
periodic_boundaries = true
# real_basis = [[-0.5, 0.5, 0.5], [0.5, -0.5, 0.5], [0.5, 0.5, -0.5]]
real_basis = [[1.0,  0.0,  0.0], [-0.33333335,  0.94280903,  0.0], [-0.33333335, -0.47140456,  0.81649655]]
unit_cell_length = 5.608132296572055
# unit_cell_length = 2.9677114487  # Angstroms -> bohr is factro 1.8897161646320724
# r_atoms = [[0.25, 0.25, 0.25]]
r_atoms = [[0.16666664, 0.23570224, 0.40824827]]
z_atoms = [3.0]
n_el_atoms = [3]
n_el = 3


[LiSolidBCC]
periodic_boundaries = true
real_basis = [[1.0,  0.0,  0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
unit_cell_length = 6.63
# unit_cell_length = 3.51  # Angstroms -> bohr is factro 1.8897161646320724
r_atoms = [[0.00, 0.00, 0.00], [0.5, 0.5, 0.5]]
z_atoms = [3.0, 3.0]
n_el_atoms = [3, 3]
n_el = 6

[LiSolidSingleAtom]
periodic_boundaries = true
real_basis = [[1.0,  0.0,  0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
unit_cell_length = 3.0
# unit_cell_length = 3.51  # Angstroms -> bohr is factro 1.8897161646320724
r_atoms = [[0.5, 0.5, 0.5]]
z_atoms = [3.0]
n_el_atoms = [3]
n_el = 3

[HeSolid]
periodic_boundaries = true
real_basis = [[1.0,  0.0,  0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
unit_cell_length = 2.0
# unit_cell_length = 3.51  # Angstroms -> bohr is factro 1.8897161646320724
r_atoms = [[0.5, 0.5, 0.5]]
z_atoms = [2.0]
n_el_atoms = [2]
n_el = 2

[HSolid]
periodic_boundaries = true
real_basis = [[1.0,  0.0,  0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
unit_cell_length = 1.0
# unit_cell_length = 3.51  # Angstroms -> bohr is factro 1.8897161646320724
r_atoms = [[0.5, 0.5, 0.5]]
z_atoms = [1.0]
n_el_atoms = [1]
n_el = 1

# check the primitive lattice
# check the reciprocal lattice
# check the unit cell unit_cell_length
# check the positions of the r_atoms
# check the number of electrons
# check the pbc procedure
# check the minimum image convention in ansatz
# check the minimum image convention in the vmc 
# check whether or not using 2pi
# check 
