
[Li]
r_atoms = [[0.0, 0.0, 0.0]]
z_atoms = [3.0]
n_el_atoms = [3]
n_el = 3

[LiH]
r_atoms = [[0.0, 0.0, 0.0], [1.595, 0.0, 0.0]]
z_atoms = [3.0, 1.0]
n_el_atoms = [3, 1]
n_el = 4

[He]
r_atoms = [[0.0, 0.0, 0.0]]
z_atoms = [2.0]
n_el_atoms = [2]
n_el = 2

[Be]
r_atoms = [[0.0, 0.0, 0.0]]
z_atoms = [4.0]
n_el_atoms = [4]
n_el = 4

[B]
r_atoms = [[0.0, 0.0, 0.0]]
z_atoms = [5.0]
n_el_atoms = [5]
n_el = 5

[C]
r_atoms = [[0.0, 0.0, 0.0]]
z_atoms = [6.0]
n_el_atoms = [6]
n_el = 6

[Ne]
r_atoms = [[0.0, 0.0, 0.0]]
z_atoms = [10.0]
n_el_atoms = [10]
n_el = 10

[HEG]
pbc = true
basis = [[1.0,  0.0,  0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
scale_cell = 1.0
spin_polarized = true

[LiSolid]
pbc = true
basis = [[1.0,  0.0,  0.0], [-0.33333335,  0.94280903,  0.0], [-0.33333335, -0.47140456,  0.81649655]]
scale_cell = 5.608132296572055
r_atoms = [[0.16666664, 0.23570224, 0.40824827]]
z_atoms = [3.0]
n_el_atoms = [3]
n_el = 3


[LiSolidBCC]
pbc = true
basis = [[1.0,  0.0,  0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
scale_cell = 6.63
atoms_from_unit_cell = true
r_atoms = [[0.00, 0.00, 0.00], [0.5, 0.5, 0.5]]
z_atoms = [3.0, 3.0]
n_el_atoms = [3, 3]
n_el = 6

[LiSolidSingleAtom]
pbc = true
atoms_from_unit_cell = true
basis = [[1.0,  0.0,  0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
scale_cell = 3.0
# unit_cell_length = 3.51  # Angstroms -> bohr is factro 1.8897161646320724
r_atoms = [[0.5, 0.5, 0.5]]
z_atoms = [3.0]
n_el_atoms = [3]
n_el = 3

[HeSolid]
pbc = true
atoms_from_unit_cell = true
basis = [[1.0,  0.0,  0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
scale_cell = 2.0
# unit_cell_length = 3.51  # Angstroms -> bohr is factro 1.8897161646320724
r_atoms = [[0.5, 0.5, 0.5]]
z_atoms = [2.0]
n_el_atoms = [2]
n_el = 2

[HSolid]
pbc = true
atoms_from_unit_cell = true
basis = [[1.0,  0.0,  0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
scale_cell = 1.0
# unit_cell_length = 3.51  # Angstroms -> bohr is factro 1.8897161646320724
r_atoms = [[0.5, 0.5, 0.5]]
z_atoms = [1.0]
n_el_atoms = [1]
n_el = 1

#The density of metallic hydrogen can be estimated roughly by taking the distance between protons to be of the order of the Bohr radius a0 = ħ2/me2 = 0.529×10−8 cm
#V.L. GINZBURG, in Physics and Astrophysics, 1985

# check the primitive lattice
# check the reciprocal lattice
# check the unit cell unit_cell_length
# check the positions of the r_atoms
# check the number of electrons
# check the pbc procedure
# check the minimum image convention in ansatz
# check the minimum image convention in the vmc 
# check whether or not using 2pi
# check 
