
# base config
base_cfg:
  exp_name: PRX_Responses/af
  n_it: 50000
  save_every: 25000

  system: HEG
  n_walkers: 1024
  n_sh: 64
  n_ph: 32
  orbitals: real_plane_waves
  n_el: 7
  n_up: 7
  opt: kfac
  n_det: 1
  density_parameter: 1.
  lr: 1e-3
  atol: 1e-6
  n_layers: 2
  correlation_length: 10
  n_pre_it: 500
  pretrain: True
  backflow_coords: True
  jastrow: False
  psplit_spins: True
  target_acceptance: 0.5
  sweep: False
  input_activation_nonlinearity: 3sin+3cos
  nonlinearity: cos

sweep:
  # bf_af: ['tanh', ]
  # seed: [0,]
  bf_af: ['tanh', 'cos', 'sin', 'silu', 'no_af']
  seed: [0,1,2]
